# Generated by Django 5.0.3 on 2024-03-04 09:21

import api.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('full_name', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('dob', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[('admin', 'Admin'), ('patient', 'Patient')], default='patient', max_length=20)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', api.manager.UserManager()),
            ],
        ),
    ]
