# Generated by Django 5.0.3 on 2024-03-05 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_healthissues_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='healthprofile',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
