# Generated by Django 5.0.1 on 2024-03-05 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_healthprofile_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='category')),
                ('health_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.healthprofile')),
            ],
        ),
        migrations.CreateModel(
            name='DietPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('health_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.healthprofile')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='exercise_videos')),
                ('video', models.FileField(blank=True, null=True, upload_to='exercise_videos')),
                ('health_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.healthprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='products')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='SymptomTips',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='symptom')),
                ('health_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.healthprofile')),
            ],
        ),
    ]
