# Generated by Django 5.0.1 on 2024-03-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_qty_appointment_communitychat_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default='0', max_digits=10),
        ),
    ]
