# Generated by Django 5.0.1 on 2024-03-12 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_order_products_order_payed'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplans',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='dietplans'),
        ),
    ]
