# Generated by Django 5.0.1 on 2024-03-13 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_dietplans_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personalchat',
            name='replay',
            field=models.TextField(blank=True, null=True),
        ),
    ]
