# Generated by Django 5.0.1 on 2024-03-14 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_order_address_order_product_order_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='payed',
            new_name='paid',
        ),
    ]
